# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.manager.name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.manager.name }}
    spec:
      containers:
        - image: informaticslab/singleuser-notebook:0.3.0
          command: ["bokeh"]
          args: ["serve","--port", "{{.Values.manager.port}}", "--allow-websocket-origin={{ .Values.manager.domain }}", "{{ .Values.manager.app_mount_path}}"]

          name: {{ .Values.manager.name }}
          ports:
            - containerPort: {{.Values.manager.port}}
          resources:
            requests:
              cpu: 50m
              memory: 1000Mi
          env:

            - name: PYTHONPATH
              value: /github_repos/forest/forest_lib/
            - name: FOREST_URL
              value: {{ .Values.manager.domain }}

          volumeMounts:
            - mountPath: {{ .Values.manager.app_mount_path}}
              name: demoapp


            - name: goofys-forest
              mountPath: /s3/stephen-sea-public-london/

      volumes:
        - name: demoapp
          configMap:
            name: demoapp

        - name: goofys-forest
          flexVolume:
            driver: "informaticslab/goofys-flex-volume"
            options:
              # Required
              bucket: "stephen-sea-public-london"
              dirMode: "0755"
              fileMode: "0777"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demoapp
data:
{{ (.Files.Glob "documents/speed_test/*.py").AsConfig | indent 2 }}
---
